easy_admin:
    entities:
      # VISA
      LpProductCat:
          class: App\Entity\LpProductCat
          label: "Libellés - Catégories de matériel"
          list:
              actions:
                    - {name: 'show', icon: 'eye', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
                    - {name: 'new', icon: 'plus', label: 'Ajouter une catégorie', css_class: 'btn btn-success'}
                    - {name: 'search', label: 'Rechercher'}
              title: "Libellés - Catégories de matériel"
              fields:
                    - { property: 'Id', label: 'N°' }
                    - { property: 'name', label: 'Libellé' }
                    - { property: 'product', label: "Nombre de matériel concerné"}

          edit:
              title: "Edition"
              fields:
                  - { property: 'name' , label: 'Nom'}
                  
          show:
              title: 'Aperçu'
              fields:
                  - { property: 'name' , label: 'Nom'}
                  - { property: 'product' , label: 'Matéirel concerné'}
          templates:
              edit: 'admin/edit/editProductCat.html.twig'



                